from datetime import datetime
from pathlib import Path

from Programma_CS2_RENAN.backend.processing.state_reconstructor import RAPStateReconstructor
from Programma_CS2_RENAN.ingestion.demo_loader import DemoLoader
from Programma_CS2_RENAN.observability.logger_setup import get_logger
from Programma_CS2_RENAN.reporting.visualizer import MatchVisualizer

_logger = get_logger("cs2analyzer.report_generator")


class MatchReportGenerator:
    def __init__(self, db_manager):
        self.db = db_manager
        self.viz = MatchVisualizer()
        self.output_dir = Path("reports")
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, demo_path):
        """
        Full pipeline: Parse -> Analyze -> Visualize -> Report.
        """
        # 1. Parse Demo
        loader = DemoLoader()
        try:
            parse_result = loader.load_demo(demo_path)
        except Exception as e:
            _logger.error("Failed to parse demo %s: %s", demo_path, e)
            return None

        if not parse_result:
            _logger.warning("Cannot generate report: empty parse result for demo %s", demo_path)
            return None

        map_name = next(iter(parse_result), "unknown")
        if map_name == "unknown":
            _logger.warning("Cannot generate report: map_name is 'unknown' for demo %s", demo_path)
            return None

        frames, events, _ = parse_result[map_name]

        if not frames:
            _logger.warning("Cannot generate report: no frames parsed for demo %s", demo_path)
            return None

        # 2. Extract Data
        player_positions = []
        deaths = []

        for frame in frames:
            for p in frame.players:
                player_positions.append((p.pos_x, p.pos_y))
                if p.health == 0:
                    deaths.append({"x": p.pos_x, "y": p.pos_y})

        if not player_positions:
            _logger.warning("Cannot generate report: no player positions extracted from %s", demo_path)
            return None

        # 3. Generate Visuals
        heatmap_path = self.viz.generate_heatmap(player_positions, map_name)

        # 4. Generate Text Report
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_filename = f"MatchReport_{map_name}_{timestamp}.md"
        report_path = self.output_dir / report_filename

        try:
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(f"# CS2 Coach Match Report\n")
                f.write(f"**Map**: {map_name}\n")
                f.write(f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")

                f.write("## 1. Positioning Heatmap\n")
                f.write("This map shows your primary areas of operation.\n")
                f.write(f"![Heatmap]({Path(heatmap_path).resolve()})\n\n")

                f.write("## 2. Fundamental Errors\n")
                f.write("- Analysis of deaths shows clustering at X, Y.\n")
                f.write("- Recommendation: Check 'Fundamentals' for hold angles in these zones.\n")

                f.write("\n> Generated by Macena CS2 Analyzer")
        except OSError as e:
            _logger.error("Failed to write report to %s: %s", report_path, e)
            return None

        return str(report_path)
