"""add_heartbeat_telemetry_to_coachstate

Revision ID: 19fcff36ea0a
Revises: da7a6be5c0c7
Create Date: 2026-01-13 10:37:15.566258

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19fcff36ea0a"
down_revision: Union[str, Sequence[str], None] = "da7a6be5c0c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coachstate", sa.Column("service_pid", sa.Integer(), nullable=True))
    op.add_column("coachstate", sa.Column("system_load_cpu", sa.Float(), nullable=False, server_default="0.0"))
    op.add_column("coachstate", sa.Column("system_load_mem", sa.Float(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coachstate", "system_load_mem")
    op.drop_column("coachstate", "system_load_cpu")
    op.drop_column("coachstate", "service_pid")
    # ### end Alembic commands ###
