"""add_last_tick_processed_to_ingestiontask

Revision ID: 609fed4b4dce
Revises: 8c443d3d9523
Create Date: 2026-01-12 13:01:51.061043

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "609fed4b4dce"
down_revision: Union[str, Sequence[str], None] = "8c443d3d9523"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingestiontask", sa.Column("last_tick_processed", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingestiontask", "last_tick_processed")
    # ### end Alembic commands ###
