"""Triple_Daemon_Support

Revision ID: 8c443d3d9523
Revises: c8a2308770e5
Create Date: 2026-01-11 16:19:29.535046

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c443d3d9523"
down_revision: Union[str, Sequence[str], None] = "c8a2308770e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coachstate", sa.Column("hltv_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="Idle")
    )
    op.add_column(
        "coachstate", sa.Column("ingest_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="Idle")
    )
    op.add_column(
        "coachstate", sa.Column("ml_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="Idle")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coachstate", "ml_status")
    op.drop_column("coachstate", "ingest_status")
    op.drop_column("coachstate", "hltv_status")
    # ### end Alembic commands ###
