"""Add_Retraining_Trigger_Support

Revision ID: c8a2308770e5
Revises: 8a93567a2798
Create Date: 2026-01-11 16:15:21.068837

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8a2308770e5"
down_revision: Union[str, Sequence[str], None] = "8a93567a2798"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coachstate", sa.Column("last_trained_sample_count", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coachstate", "last_trained_sample_count")
    # ### end Alembic commands ###
